groups:
  - name: 服务器资源监控
    rules:
      - alert: 内存使用率过高
        #    expr: (node_memory_Buffers_bytes+node_memory_Cached_bytes+node_memory_MemFree_bytes)/node_memory_MemTotal_bytes*100 > 90
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 90
        for: 5m  # 告警持续时间，超过这个时间才会发送给alertmanager
        labels:
          severity: 严重告警
        annotations:
          summary: "{{ $labels.instance }} 内存使用率过高，请尽快处理！"
          description: "{{ $labels.instance }}内存使用率超过90%,当前使用率{{ $value }}%."

      - alert: 服务器宕机
        expr: up == 0
        for: 3m
        labels:
          severity: 严重告警
        annotations:
          summary: "{{$labels.instance}} 服务器宕机，请尽快处理！"
          description: "{{$labels.instance}} 服务器延时超过3分钟，当前状态{{ $value }}. "

      - alert: CPU高负荷
        expr: 100 - (avg by (instance,job)(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 5m
        labels:
          severity: 严重告警
        annotations:
          summary: "{{$labels.instance}} CPU使用率过高，请尽快处理！"
          description: "{{$labels.instance}} CPU使用大于90%，当前使用率{{ $value }}%. "

      - alert: 磁盘IO性能
        expr: avg(irate(node_disk_io_time_seconds_total[1m])) by(instance,job)* 100 > 90
        for: 5m
        labels:
          severity: 严重告警
        annotations:
          summary: "{{$labels.instance}} 流入磁盘IO使用率过高，请尽快处理！"
          description: "{{$labels.instance}} 流入磁盘IO大于90%,当前使用率{{ $value }}%."


      - alert: 网络流入
        expr: ((sum(rate (node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])) by (instance,job)) / 100) > 102400
        for: 5m
        labels:
          severity: 严重告警
        annotations:
          summary: "{{$labels.instance}} 流入网络带宽过高，请尽快处理！"
          description: "{{$labels.instance}} 流入网络带宽持续5分钟高于100M. RX带宽使用量{{$value}}."

      - alert: 网络流出
        expr: ((sum(rate (node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])) by (instance,job)) / 100) > 102400
        for: 5m
        labels:
          severity: 严重告警
        annotations:
          summary: "{{$labels.instance}} 流出网络带宽过高,请尽快处理！"
          description: "{{$labels.instance}} 流出网络带宽持续5分钟高于100M. RX带宽使用量{$value}}."

      - alert: TCP连接数
        expr: node_netstat_Tcp_CurrEstab > 10000
        for: 2m
        labels:
          severity: 严重告警
        annotations:
          summary: " TCP_ESTABLISHED过高！"
          description: "{{$labels.instance}} TCP_ESTABLISHED大于100%,当前使用率{{ $value }}%."

      - alert: 磁盘容量
        expr: (node_filesystem_size_bytes{fstype=~"ext.?|xfs"}-node_filesystem_free_bytes{fstype=~"ext.?|xfs"}) *100/(node_filesystem_avail_bytes {fstype=~"ext.?|xfs"}+(node_filesystem_size_bytes{fstype=~"ext.?|xfs"}-node_filesystem_free_bytes{fstype=~"ext.?|xfs"})) > 90
        for: 1m
        labels:
          severity: 严重告警
        annotations:
          summary: "{{$labels.mountpoint}} 磁盘分区使用率过高，请尽快处理！"
          description: "{{$labels.instance}} 磁盘分区使用大于90%，当前使用率{{ $value }}%."

      # Nginx 请求处理时间过高
      - alert: Nginx请求处理时间过高
        expr: avg(nginx_http_request_duration_seconds_sum) by (instance) / avg(nginx_http_requests_total) by (instance) > 1
        for: 5m
        labels:
          severity: 严重告警
        annotations:
          summary: "{{$labels.instance}} Nginx请求处理时间过高，请尽快处理！"
          description: "{{$labels.instance}} 的 Nginx 请求处理时间超过1秒，请检查 Nginx 配置或负载情况。"

      # Nginx 5xx 错误率过高
      - alert: Nginx 5xx 错误率过高
        expr: rate(nginx_http_requests_total{status=~"5.."}[5m]) / rate(nginx_http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: 严重告警
        annotations:
          summary: "{{$labels.instance}} Nginx 5xx 错误率过高，请尽快处理！"
          description: "{{$labels.instance}} 的 Nginx 5xx 错误率超过5%。"

      # Nginx 活动连接数过多
      - alert: Nginx活动连接数过多
        expr: nginx_nginx_connections_active > 1000
        for: 5m
        labels:
          severity: 严重告警
        annotations:
          summary: "{{$labels.instance}} Nginx 活动连接数过多，请尽快处理！"
          description: "{{$labels.instance}} 的 Nginx 活动连接数超过1000，请检查 Nginx 配置或负载情况。"

      # Nginx 请求数过多
      - alert: Nginx请求数过多
        expr: rate(nginx_http_requests_total[5m]) > 1000
        for: 5m
        labels:
          severity: 严重告警
        annotations:
          summary: "{{$labels.instance}} Nginx 请求数过多，请尽快处理！"
          description: "{{$labels.instance}} 在过去5分钟内的请求数超过1000，请检查流量或服务器负载。"
